//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.FileSystemProvider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.FileSystemProvider.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the file or folder was created.
        /// </summary>
        internal static string DateCreatedDescription {
            get {
                return ResourceManager.GetString("DateCreatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        internal static string DateCreatedLabel {
            get {
                return ResourceManager.GetString("DateCreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the file or folder was modified.
        /// </summary>
        internal static string DateModifiedDescription {
            get {
                return ResourceManager.GetString("DateModifiedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        internal static string DateModifiedLabel {
            get {
                return ResourceManager.GetString("DateModifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a logical drive on this computer.
        /// </summary>
        internal static string DriveCategoryDescription {
            get {
                return ResourceManager.GetString("DriveCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        internal static string DriveCategoryLabel {
            get {
                return ResourceManager.GetString("DriveCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file on your local drive.
        /// </summary>
        internal static string FileCategoryDescription {
            get {
                return ResourceManager.GetString("FileCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileCategoryLabel {
            get {
                return ResourceManager.GetString("FileCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FileGroup {
            get {
                return ResourceManager.GetString("FileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size in bytes.
        /// </summary>
        internal static string FileSizeDescription {
            get {
                return ResourceManager.GetString("FileSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        internal static string FileSizeLabel {
            get {
                return ResourceManager.GetString("FileSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        internal static string FileSystemGroup {
            get {
                return ResourceManager.GetString("FileSystemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string FileSystemViewLabel {
            get {
                return ResourceManager.GetString("FileSystemViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder on your local drive.
        /// </summary>
        internal static string FolderCategoryDescription {
            get {
                return ResourceManager.GetString("FolderCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string FolderCategoryLabel {
            get {
                return ResourceManager.GetString("FolderCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string FolderGroup {
            get {
                return ResourceManager.GetString("FolderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether a directory is a mounted folder.
        /// </summary>
        internal static string MountedFolderCategoryDescription {
            get {
                return ResourceManager.GetString("MountedFolderCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounted folder.
        /// </summary>
        internal static string MountedFolderCategoryLabel {
            get {
                return ResourceManager.GetString("MountedFolderCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the file is read only.
        /// </summary>
        internal static string ReadOnlyDescription {
            get {
                return ResourceManager.GetString("ReadOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only.
        /// </summary>
        internal static string ReadOnlyLabel {
            get {
                return ResourceManager.GetString("ReadOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates a symbolic link connection.
        /// </summary>
        internal static string SymbolicLinkCategoryDescription {
            get {
                return ResourceManager.GetString("SymbolicLinkCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbolic link.
        /// </summary>
        internal static string SymbolicLinkCategoryLabel {
            get {
                return ResourceManager.GetString("SymbolicLinkCategoryLabel", resourceCulture);
            }
        }
    }
}
